[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]
